backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'event'
    label: 'Event'
    folder: 'src/pages/event'
    create: true
    slug: '{{slug}}-{{day}}-{{month}}-{{year}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'EventPost',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD HH:mm',
        }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'board'
    label: 'Board'
    folder: 'src/pages/board'
    create: true
    slug: '{{slug}}-{{year}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
        label: 'Identifier',
        name: 'identifier',
        widget: 'hidden',
        default: 'board',
      }
      - { label: 'Year', name: 'year', widget: 'date', format: 'YYYY' }
      - { label: 'Description', name: 'description', widget: 'markdown'}
      - { label: 'Picture', name: 'picture', widget: 'image'}
  - name: 'site'
    label: 'Site'
    files:
      - file: 'src/pages/site/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: '',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - {
              label: 'Identifier',
              name: 'identifier',
              widget: 'hidden',
              default: 'about',
            }
      - file: 'src/pages/site/contact.md'
        label: 'Contact'
        name: 'contact'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - {
              label: 'Identifier',
              name: 'identifier',
              widget: 'hidden',
              default: 'contact',
            }
      - file: 'src/pages/site/membership.md'
        label: 'Membership'
        name: 'membership'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - {
              label: 'Identifier',
              name: 'identifier',
              widget: 'hidden',
              default: 'membership',
            }
      - file: 'src/pages/site/sponsors.md'
        label: 'Sponsors'
        name: 'sponsors'
        fields: 
          - {
              label: 'Identifier',
              name: 'identifier',
              widget: 'hidden',
              default: 'sponsors',
            }
          - label: 'Sponsor Logos'
            name: 'sponsorlogos'
            widget: 'list' 
            fields:
              - { label: 'Logo', name: 'logo', widget: 'image'}
              - { label: 'URL', name: 'url', widget: 'string'}
  - name: 'config'
    label: 'Config'
    files:
      - file: 'src/pages/config.md'
        create: true
        label: 'Config'
        name: 'config'
        widget: 'object'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: '',
            }
          - {
            label: 'Identifier',
            name: 'identifier',
            widget: 'hidden',
            default: 'config',
          }
          - {
              label: 'Header',
              name: 'header',
              widget: 'image',
              default: 'static/img/header-bg.jpg',
            }
